### PR TITLE
Add SELinux triggers for SELinux-enabled hosts

### PR DESCRIPTION
**Pull request by a-palchikov**
Fixes https://github.com/gravitational/robotest/issues/201.

I will validate the change manually before merging.

### CODE REVIEW

**Comment by a-palchikov** [comment]
I'm not sure whether there are `correct` images w.r.t SELinux - `rhel` and `CentOS` have SELinux turned on by default - as if it's configuration by convention. I would be surprised to have a corresponding OS distro (from the two mentioned) image where it was disabled by default.

**Comment by wadells** [comment]
> I'm not sure whether there are `correct` images w.r.t SELinux - `rhel` and `CentOS` have SELinux turned on by default - as if it's configuration by convention. I would be surprised to have a corresponding OS distro (from the two mentioned) image where it was disabled by default.

I think I I understand now. This change will turn all of our RHEL (we don't run any at the moment because of #182)  and CentOS (which is regularly tested) test runs into SELinux test runs.

Do we care about testing RHEL/CentOs without Gravity's SELinux support?  E.g is that an important use case to customers in the field and/or have interesting different code paths?

Effectively, I'm trying to figure out if using SELinux should be configurable, and if so how that configuration is provided to Robotest consumers.  If you don't think it needs to be configurable (a.k.a Gravity on CentOS/RHEL without SELinux isn't used or isn't likely to regress), that makes life easy, and there is no more work to do in Robotest.

**Comment by wadells** [comment]
> I'm not sure whether there are `correct` images w.r.t SELinux - `rhel` and `CentOS` have SELinux turned on by default - as if it's configuration by convention. I would be surprised to have a corresponding OS distro (from the two mentioned) image where it was disabled by default.

I guess I'm a bit confused then.  AFAIK we didn't support SELinux in Gravity until recently, ergo the centos we've been testing against must have had it disabled.

**Comment by wadells** [comment]
Sorry about the accidental close. :smile:  I was trying to discard an earlier draft of my comment above.

**Comment by a-palchikov** [comment]
I think it would be beneficial to test both sides on rhel or CentOS (does not have to be both distributions for each configuration though).

**Pull request merged**
